### ISSUE TITLE
[Fatal Error] :23:66: 1은(는) 1바이트 UTF-8 시퀀스에 대해 부적합한 바이트입니다.

### ISSUE THREAD

**Issue by k0kao** [ryanking13/android-SSL-unpinning#1]
안녕하세요 해당 tool을 사용하던도중 아래와 같이 오류가납니다. 

I: Using Apktool 2.5.0 on com.nexon.handsplus_42.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\k\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Using Apktool 2.5.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
[Fatal Error] :23:66: 1은(는) 1바이트 UTF-8 시퀀스에 대해 부적합한 바이트입니다.
I: Checking whether resources has changed...
I: Building resources...

다른 어플은 잘 되는데 유독 "메이플 핸즈+" 해당어플만 안됩니다.

어떻게 해야 오류를 해결할수있을까요??

**Comment by ryanking13** [comment]
한글 때문에 인코딩 문제가 발생했네요.

수정하였는데(#2) 최신 버전으로 다시 pull해서 실행해보시고 여전히 오류가 발생하면 알려주세요.
